/**
 * Dose Model
 * Defines the data structure for dose records
 * Note: Doses are generated by Cloud Functions, not created directly by clients
 */

/**
 * Creates a dose data object
 * @param {Object} data - Dose data
 * @returns {Object} - Dose object
 */
export function createDoseData(data) {
  return {
    medicineId: data.medicineId || '',
    scheduleId: data.scheduleId || '',
    parentId: data.parentId || '',
    medicineName: data.medicineName || '',
    dosageAmount: data.dosageAmount || 0,
    dosageUnit: data.dosageUnit || '',
    scheduledTime: data.scheduledTime || new Date(),
    status: data.status || 'pending', // pending, taken, missed, skipped
    createdAt: data.createdAt || new Date(),
  };
}

/**
 * Validates dose data structure
 * @param {Object} data - Dose data to validate
 * @returns {Object} - { isValid: boolean, errors: Object }
 */
export function validateDose(data) {
  const errors = {};

  if (!data.medicineId || typeof data.medicineId !== 'string') {
    errors.medicineId = 'Medicine ID is required';
  }

  if (!data.scheduleId || typeof data.scheduleId !== 'string') {
    errors.scheduleId = 'Schedule ID is required';
  }

  if (!data.parentId || typeof data.parentId !== 'string') {
    errors.parentId = 'Parent ID is required';
  }

  if (!data.medicineName || typeof data.medicineName !== 'string') {
    errors.medicineName = 'Medicine name is required';
  }

  if (typeof data.dosageAmount !== 'number' || data.dosageAmount <= 0) {
    errors.dosageAmount = 'Dosage amount must be a positive number';
  }

  if (!data.dosageUnit || typeof data.dosageUnit !== 'string') {
    errors.dosageUnit = 'Dosage unit is required';
  }

  if (!data.scheduledTime || !(data.scheduledTime instanceof Date)) {
    errors.scheduledTime = 'Scheduled time must be a valid Date';
  }

  const validStatuses = ['pending', 'taken', 'missed', 'skipped'];
  if (!data.status || !validStatuses.includes(data.status)) {
    errors.status = 'Status must be one of: pending, taken, missed, skipped';
  }

  return {
    isValid: Object.keys(errors).length === 0,
    errors,
  };
}
